### ISSUE TITLE
网页版运行完成后，页面显示不出来

### ISSUE THREAD

**Issue by zczzz** [zz570557024/vue-mpvue-ChatRobot#2]
运行网页版，在浏览器上有报错，页面显示不出来
![wx20180608-101704](https://user-images.githubusercontent.com/13907161/41135782-c8b34b74-6b05-11e8-8661-f4e7fc188503.png)

**Comment by zz570557024** [comment]
由于vue.all.js文件加载失败,
你可以尝试更换路径，重新加载。
我下午更新一个加强版的，静态文件依赖。
@zczzz

**Comment by zczzz** [comment]
好的，谢谢

**Comment by zz570557024** [comment]
已更新。
